//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zmap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AboutU
    {
        public int Id { get; set; }
        public string HeaderTitle { get; set; }
        public string HeaderDetails { get; set; }
        public string BodyTitle { get; set; }
        public string BodyDetails1 { get; set; }
        public string BodyDetails2 { get; set; }
        public string PhotoUrl { get; set; }
    }
}
