//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zmap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public int Id { get; set; }
        public string ActivityName { get; set; }
        public Nullable<double> CostWithTransportation { get; set; }
        public Nullable<bool> Morning { get; set; }
        public Nullable<bool> Evening { get; set; }
        public int CompanyId { get; set; }
        public int ActivityCategoryId { get; set; }
        public string Description { get; set; }
        public Nullable<double> CostWithoutTrasnportation { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> CreatedByUserId { get; set; }
        public Nullable<int> ModifiedByUserId { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> ActivityDate { get; set; }
        public Nullable<int> SubAreaId { get; set; }
        public string Safety { get; set; }
        public Nullable<int> CityID { get; set; }
    }
}
