//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zmap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string About { get; set; }
        public string PrivacyPolicy { get; set; }
        public Nullable<bool> IsExternal { get; set; }
        public Nullable<bool> IsInternal { get; set; }
        public Nullable<bool> IsActivity { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> CreatedByUserId { get; set; }
        public Nullable<int> ModifiedByUserId { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> IsConfirmed { get; set; }
        public string ManagerPhonenumber { get; set; }
        public string ManagerEmail { get; set; }
    }
}
