//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zmap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserReservation
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public Nullable<int> HotelId { get; set; }
        public Nullable<int> RoomId { get; set; }
        public Nullable<int> TransportationCompanyId { get; set; }
        public Nullable<int> BusId { get; set; }
        public Nullable<int> StationId { get; set; }
        public Nullable<int> ActivityCompanyId { get; set; }
        public Nullable<int> NumberOfSeats { get; set; }
        public Nullable<double> AccommodationCost { get; set; }
        public Nullable<double> TransportationCost { get; set; }
        public Nullable<double> ActivityCost { get; set; }
        public Nullable<double> TotalCost { get; set; }
        public Nullable<System.DateTime> DateFrom { get; set; }
        public Nullable<System.DateTime> DateTo { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> RoomAvailabilityId { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> UserPaymentId { get; set; }
        public Nullable<int> NumberOfAdults { get; set; }
        public Nullable<int> NumberOfChilderLessThanSix { get; set; }
        public Nullable<int> NumberOfChildernBetweenSixAndTwelve { get; set; }
        public string HotelNote { get; set; }
        public string TransportationNote { get; set; }
        public string ActivityNote { get; set; }
        public Nullable<bool> ApprovedByAdmin { get; set; }
        public Nullable<bool> UserConfirmation { get; set; }
        public Nullable<int> HomeId { get; set; }
        public Nullable<int> DestinationId { get; set; }
    }
}
